/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.exactpro.th2.gradle

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class Th2GradlePluginPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'com.exactpro.th2.gradle.greeting'")
            }
        }
    }
}
