name: build and test gradle project

on:
  push:
    branches-ignore:
    - master
    - version-*
    - dependabot*
    paths-ignore:
      - README.md

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build
