/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.exactpro.th2.gradle

import java.io.File
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

/**
 * A simple functional test for the 'com.exactpro.th2.gradle.greeting' plugin.
 */
class Th2GradlePluginPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('java')
                id('maven-publish')
                id('com.exactpro.th2.gradle.publish')
            }
            
            th2Publish {
              pom {
                vcsUrl.set("test")
              }
              sonatype {
                username.set("username")
                password.set("password")
              }
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
//        runner.withArguments("greeting")
        runner.withProjectDir(projectDir)
        runner.withArguments("--stacktrace", "tasks")
        val result = runner.build()

        // Verify the result
//        assertTrue(result.output.contains("Hello from plugin 'com.exactpro.th2.gradle.greeting'"))
    }
}
