name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
    - name: Run CI action
      uses: th2-net/ci-github-action@master
      with:
        ref: ${{ github.sha }}
