name: verify gradlePlugin configuration

on:
  push:
    branches-ignore:
    - master
    - version-*
    - dependabot*
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: gradle clean publishPlugins --info --validate-only -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
