name: verify gradlePlugin configuration

on:
  push:
    paths-ignore:
      - README.md

jobs:
  test:
    # dependabot does not have access to organization secrets
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: wrapper
          validate-wrappers: 'true'
      - name: Validate Gradle portal publication configuration
        run: >
          ./gradlew clean publishPlugins --info --validate-only
          -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
          -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
