name: Update version
on:
  workflow_call:
    inputs:
      current-version:
        type: string
        description: "current version to be replaced"
      next-version:
        type: string
        description: "next version to be inserted"
    secrets:
      PUSH_PAT:
        required: true
        description: Token with push rights to allow creating PR, triggering workflows and merging the PR after that
  # Just for test purposes
  workflow_dispatch:
    inputs:
      current-version:
        type: string
        description: "current version to be replaced"
      next-version:
        type: string
        description: "next version to be inserted"
jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "NEW_BRANCH=new-version-${{ inputs.next-version }}" >> $GITHUB_ENV
      - name: Prepare next dev version
        id: prepare_next_dev
        run: |
          sed -i -e 's/${{ inputs.current-version }}/${{ inputs.next-version }}/g' gradle.properties
      - name: Commit next dev version
        id: commit_next_dev
        uses: EndBug/add-and-commit@v9
        with:
          add: "['gradle.properties']"
          default_author: github_actions
          message: "Prepare next version"
          new_branch: ${{ env.NEW_BRANCH }}
      - name: Create PR for version update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh pr create --title "Prepare next version"
          --body "Automated version update"
          --head ${{ env.NEW_BRANCH }}
          --base master
          --reviewer Nikita-Smirnov-Exactpro
          --label ignore